version: '3'

services:

  postgres:
    image: postgres:10
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    ports:
      - 5432:5432

  webserver:
    hostname: webserver
    image: dagger/airflow:${AIRFLOW_VERSION}
    depends_on:
      - postgres
    environment:
      - AIRFLOW_HOME=${AIRFLOW_HOME}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=zdkf0niohVjv_9RcdBOj3MpRz6gYr1T_2okkA8KRk-w=
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - PYTHONPATH=${AIRFLOW_HOME}
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=airflow
      - POSTGRES_DB=airflow
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=airflow
      - NAVBAR_COLOR=currentColor
      - REMOTE_LOGGING=False
      - ENV=local
    volumes:
      - ${AIRFLOW_DAGS_DIR}:${AIRFLOW_HOME}/dags
      - ${DAGGER_DIR}:${AIRFLOW_HOME}/dagger
      - ${DAGGER_DIR}/logs:${AIRFLOW_HOME}/logs
    ports:
        - 8080:8080
    command: webserver

  scheduler:
    hostname: scheduler
    image: dagger/airflow:${AIRFLOW_VERSION}
    depends_on:
      - postgres
    environment:
      - AIRFLOW_HOME=${AIRFLOW_HOME}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=zdkf0niohVjv_9RcdBOj3MpRz6gYr1T_2okkA8KRk-w=
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - PYTHONPATH=${AIRFLOW_HOME}
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=airflow
      - POSTGRES_DB=airflow
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=airflow
      - REMOTE_LOGGING=False
      - AIRFLOW__LOGGING__COLORED_CONSOLE_LOG=False
      - ENV=local
    volumes:
      - ${AIRFLOW_DAGS_DIR}:${AIRFLOW_HOME}/dags
      - ${DAGGER_DIR}:${AIRFLOW_HOME}/dagger
      - ${DAGGER_DIR}/logs:${AIRFLOW_HOME}/logs
    command: scheduler

  neo4j:
    image: neo4j:4.1.4
    container_name: neo4j_dagger
    depends_on:
      - elasticsearch
    environment:
      - NEO4J_AUTH=neo4j/test
    ulimits:
      nofile:
        soft: 40000
        hard: 40000
    ports:
      - 7474:7474
      - 7687:7687
    expose:
      - 7687
    volumes:
        - ${DOCKERS_DIR}/neo4j/conf:/conf
        - ${DOCKERS_DIR}/neo4j/plugins:/plugins
        - /tmp/neo4j/data:/neo4j/data
        - /tmp/neo4j/log:/var/log/neo4j

  elasticsearch:
    image: elasticsearch:7.16.2
    container_name: es
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ${DOCKERS_DIR}/elasticsearch/data:/usr/share/elasticsearch/data

  dagger_ui:
    depends_on:
      - elasticsearch
      - neo4j
    image: dagger/dagger_ui:v0.1
    container_name: dagger_ui
    ports:
      - 5000:5000
    volumes:
      - ${DAGGER_DIR}/../dagger_ui/app:/usr/local/dagger/app
